#!/bin/bash
# trccmd
# A simple wrapper over the useful trace-cmd front-end to ftrace
#
# Kaiwan NB, kaiwanTECH
name=$(basename $0)
TRC_FILE=/tmp/trc.txt
WANT_TRCOMP_REP=0   # set to 1 to get the 'Trace Compass' format report file; YMMV :-p
TRC_FILE_TRCOMP=/tmp/trc_trcomp.txt  # for Trace Compass

## "main" here
[ $(id -u) -ne 0 ] && {
 echo "${name}: Need to be root."
 exit 1
}
# TODO - update to check for tracefs fs
echo -n "[+] Checking for ftrace support ..."
mount |grep -q -w debugfs || {
 echo "${name}: debugfs filesystem not mounted? Aborting..."
 exit 2
}
TRCMNT=$(mount |grep -w debugfs |awk '{print $3}')
export TRCMNT=${TRCMNT}/tracing
[ ! -d ${TRCMNT} ] && {
 echo "${name}: ${TRCMNT} not mounted as debugfs? Aborting..."
 exit 2
}
echo " [OK] (ftrace loc: ${TRCMNT})"

which trace-cmd >/dev/null 2>&1 || {
  echo "${name}: trace-cmd not installed (or not in PATH)?"
  exit 1
 }
echo "trace-cmd [OK]"

[ $# -lt 1 ] && {
 echo
 echo "Usage: ${name} program-to-ftrace-via-trace-cmd
 Eg. sudo ./${name} ps -LA
 [NOTE: this will perform an _exclusive_ ftrace of the provided app (ps in this eg)]"
 exit 3
}

echo "[+] Recording now ..."
trace-cmd record -p function_graph -F "$@" || {
  echo "${name}: 'trace-cmd record' failed, aborting ..."
  exit 4
}

echo "[+] Reporting now (ftrace) ..."
echo "    Note: report done in latency format, *leaving out* interrupt contexts"
trace-cmd report -i ./trace.dat -I -S -l > ${TRC_FILE} || {
  echo "${name}: 'trace-cmd report' failed, aborting ..."
  exit 5
}
echo "[+] Done, report: ${TRC_FILE}"
ls -lh ${TRC_FILE}

[ ${WANT_TRCOMP_REP} -eq 1 ] && {
# For LTTng TraceCompass GUI: record with -R     << not working w/ tracecompass?? >>
echo "[+] Reporting now (for TraceCompass with -R;   YMMV, of course) ..."
echo "    Note: report done in latency format, *leaving out* interrupt contexts"
#trace-cmd report -i ./trace.dat -I -S -l -R > ${TRC_FILE_TRCOMP} || {
trace-cmd report -i ./trace.dat -R > ${TRC_FILE_TRCOMP} || {
  echo "${name}: 'trace-cmd report' failed, aborting ..."
  exit 5
}
echo "[+] Done, report: ${TRC_FILE_TRCOMP}"
ls -lh ${TRC_FILE_TRCOMP}
} || echo "[Skipping (iffy) Trace Compass report file...]"

exit 0
